name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: terraform

jobs:

#############################################
# DEV PLAN
#############################################

  plan-dev:

    runs-on: ubuntu-latest

    environment: dev

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      # - name: Azure Login using OIDC
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debug secrets
        run: |
          echo "Client ID present: ${{ secrets.AZURE_CLIENT_ID != '' }}"
          echo "Tenant ID present: ${{ secrets.AZURE_TENANT_ID != '' }}"
          echo "Subscription ID present: ${{ secrets.AZURE_SUBSCRIPTION_ID != '' }}"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=dev.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan DEV
        run: |
          terraform plan \
            -var-file=env/dev.tfvars

#############################################
# TEST PLAN
#############################################

  plan-test:

    runs-on: ubuntu-latest

    environment: test

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      # - name: Azure Login using OIDC
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=test.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan TEST
        run: |
          terraform plan \
            -var-file=env/test.tfvars

#############################################
# PROD PLAN
#############################################

  plan-prod:

    runs-on: ubuntu-latest

    environment: prod

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      # - name: Azure Login using OIDC
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=prod.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan PROD
        run: |
          terraform plan \
            -var-file=env/prod.tfvars