name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

#############################################
# DEV
#############################################

  terraform-dev:

    runs-on: ubuntu-latest

    environment: dev

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Set ARM variables for OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=dev.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=env/dev.tfvars

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file=env/dev.tfvars

#############################################
# TEST
#############################################

  terraform-test:

    needs: terraform-dev

    runs-on: ubuntu-latest

    environment: test

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Set ARM variables for OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=test.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=env/test.tfvars

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file=env/test.tfvars

#############################################
# PROD
#############################################

  terraform-prod:

    needs: terraform-test

    runs-on: ubuntu-latest

    environment: prod

    defaults:
      run:
        working-directory: terraform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Set ARM variables for OIDC
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=prod.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=env/prod.tfvars

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file=env/prod.tfvars